[package]
name = "makepad-rope"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"

[[bench]]
name = "bench"
harness = false

[dev-dependencies]
criterion = "0.3.6"
proptest = "1.0.0"
