[package]
name = "makepad-procmac-example"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Procmacro example"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
makepad-macro-lib = { path = "../../../platform/macro_lib", version = "0.1" }


