[package]
name = "makepad-live-tokenizer"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad platform live DSL tokenizer"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"
metadata.makepad-auto-version = "Lbtw64Uajgi0s-chG0zl3iUwEJg="

[dependencies]
makepad-math = { path = "../../libs/math", version = "0.3.0" }
makepad-micro-serde = { path = "../../libs/micro_serde", version = "0.3.0" }
makepad-live-id = { path = "../../libs/live_id", version = "0.3.0"}
