[package]
name = "makepad-regex"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"

[dependencies]
makepad-range-set = { path = "../range_set" }
makepad-varint = { path = "../varint" }